Consensys/go-corset

pkg/cmd/check.go, pkg/schema/builder.go
This downgrades missing input columns to warnings.  By default, they are still reported as errors but if the `--warn` switch is provided then they are ignored.
=> feat: Downgrade Missing Input Columns to Warning

go.mod, go.sum, pkg/cmd/check.go, pkg/cmd/util.go, pkg/util/field_array.go
This enables logging of some reasonably primitive performance stats. Particular, execution time and memory usage.
=> feat: Support Performance Stats

pkg/hir/parser.go, pkg/schema/assignment/interleave.go, testdata/interleave_01.lisp, testdata/interleave_02.lisp, testdata/interleave_03.lisp, testdata/interleave_04.lisp
This brings the syntax closer to the original corset language.
=> feat: change `interleave` to `definterleaved`

pkg/air/expr.go, pkg/binfile/computation.go, pkg/corset/ast.go, pkg/corset/binding.go, pkg/corset/compiler.go, pkg/corset/environment.go, pkg/corset/parser.go, pkg/corset/resolver.go, pkg/corset/scope.go, pkg/corset/translator.go, pkg/hir/expr.go, pkg/mir/expr.go, pkg/schema/schemas.go, pkg/trace/context.go
This puts in place a fairly serious rewrite of the name resolution algorithm.  The final design is quite robust and easily extendible.
=> Reimplement Name Resolution Algorithm

pkg/corset/binding.go, pkg/corset/resolver.go, pkg/corset/stdlib.lisp, testdata/bin-dynamic.lisp, testdata/bin-static.lisp, testdata/memory.lisp, testdata/wcp.lisp
This updates to the original standard library used by corset.  In order to get this to work, some fixes related to function overloading were required.
=> feat: update standard library

pkg/corset/expression.go, pkg/corset/parser.go, testdata/wcp.lisp
This updates the wcp example so that it reflects its original formulation exactly.
=> feat: update wcp example

pkg/mir/const.go, pkg/schema/assignment/computation.go
This improves the constant propagation a little so that terms involving multiple arithmetic constants are always reduced.
=> feat: improved constant propagation

pkg/air/gadgets/column_sort.go, pkg/air/gadgets/expand.go, pkg/air/gadgets/normalisation.go, pkg/cmd/debug.go
This improves the debug stats output.
=> feat: tidy up debug stats

pkg/cmd/check.go, pkg/schema/schemas.go, pkg/util/field_array.go
This puts in place some minor tweaks for parllel constraint checking, such as improved logging.
=> feat: tweak parallel constraint checking

go.mod, go.sum, pkg/cmd/inspect.go, pkg/trace/printer.go, pkg/util/table.go, pkg/util/termio/escapes.go, pkg/util/termio/terminal.go, pkg/util/termio/widget/separator.go, pkg/util/termio/widget/table.go, pkg/util/termio/widget/tabs.go, pkg/util/termio/widget/text.go, pkg/util/termio/window.go
This puts in place a preliminary trace inspector which is actually usable, even if a little rough around the edges.
=> feat: trace inspector

pkg/cmd/inspect.go
Whilst this doesn't fully resolve the flicker issue, it does improve it significantly when the terminal is at rest.  The issue is related to the keyboard in some way which I didn't get figure out.
=> feat: improve flicker when at rest

pkg/util/termio/terminal.go
The essential problem with pasting was that the terminal reader was not setup to handle more than one character at a time.
=> feat: support pasting into terminal

pkg/cmd/trace.go, pkg/cmd/tracediff.go
This incorporates the trace diff functionality from the trace diagnostic tool, as this was useful in diagnosing corrupted trace files.
=> feat: add "trace diff" command

pkg/air/gadgets/bits.go, pkg/air/gadgets/column_sort.go, pkg/air/gadgets/expand.go, pkg/air/gadgets/lexicographic_sort.go, pkg/air/gadgets/normalisation.go, pkg/air/schema.go, pkg/air/term.go, pkg/cmd/check.go, pkg/cmd/coverage.go, pkg/cmd/util.go, pkg/hir/expr.go, pkg/hir/lower.go, pkg/hir/schema.go, pkg/hir/util.go, pkg/mir/lower.go, pkg/mir/schema.go, pkg/schema/assertion.go, pkg/schema/constraint/lookup.go, pkg/schema/constraint/permutation.go, pkg/schema/constraint/range.go, pkg/schema/constraint/vanishing.go, pkg/schema/coverage.go, pkg/schema/schema.go, pkg/schema/schemas.go, pkg/util/collection/bit/bit_set.go, pkg/util/collection/bit/bit_test.go
This initial command is fairly rough, but it is digging out suitable data.  As such, it provides a gateway to understand the coverage results.
=> feat: add initial coverage command

pkg/cmd/coverage.go, pkg/schema/constraint/lookup.go
This puts in place a relatively basic query for looking at overall results for modules.
=> feat: support module coverage query

pkg/binfile/binfile.go, pkg/cmd/compile.go, pkg/cmd/debug.go
This now enables metadata to be embedded and specified from the command-line.  Metadata is always stored internally as JSON.
=> feat: support embedded metadata

pkg/cmd/trace.go
This adds support for reporting summaries of a trace on a module-by-module basis.
=> feat: support module trace summaries

pkg/mir/const.go, pkg/util/arrays.go
There is quite a bit more which could be done here, tbh.
=> feat: simplify air expressions involving subtraction

.github/workflows/build.yml, pkg/binfile/binfile.go, pkg/cmd/generate.go, pkg/corset/compiler.go, pkg/corset/compiler/scope.go, pkg/corset/source_map.go
This adds support for generate `Trace.java` files from a given binary zk file.
=> feat: trace generation

pkg/cmd/trace.go
This adds some counters for counting non-zero cells in columns and modules.
=> feat: support nonzero cell counters

pkg/binfile/binfile.go, pkg/cmd/compile.go, pkg/cmd/debug.go, pkg/cmd/generate.go, pkg/cmd/trace.go, pkg/cmd/util.go, pkg/trace/lt/header.go, pkg/util/collection/typed/map.go, pkg/util/collection/typed/map_test.go
This supports metadata which is structured (i.e. can be nested), which allows a more meaningful output to be produced.
=> feat: support structured metadata

pkg/cmd/coverage.go, pkg/cmd/coverage/calcs.go
This adds support for defining the titles to be used with each coverage report, making the final report a little nicer.  Also, the tool shifts from just using integers for reporting to a mixture of int / float. This allows percentages to be reported with decimal points.
=> feat: support coverage titles

pkg/cmd/generate.go, pkg/cmd/util.go, pkg/schema/builder.go, pkg/schema/schemas.go
This adds a check on the amount a trace is expanded to ensure it coincides with the expected amount.
=> feat: add spillage check

pkg/cmd/inspector/inspect.go, pkg/cmd/inspector/module_view.go
=> fix: inspector goto row

pkg/corset/compiler/resolver.go
This puts in place a straightforward fix for error over-reporting.  The issue was that resolution stopped in a given module on the first iteration where an error was encountered.  This could potentially leave unfinislied declarations in that module (even when they could have been finalised).  For the root module (where the stdlib lives) this was particularly problematic.
=> fix: error over reporting

pkg/mir/const.go, pkg/mir/expr.go, pkg/mir/lower.go, pkg/mir/optimiser.go, pkg/util/interval.go
This improves the mechanism for handling constant propagation at the MIR level, in particular in the presence of casts.
=> feat: improved constant propagation at MIR level

pkg/cmd/check.go, pkg/mir/context.go, pkg/schema/constraint/lookup.go, pkg/schema/constraint/range.go, pkg/schema/constraint/sorted.go, pkg/schema/constraint/vanishing.go, pkg/schema/schema.go
This puts through a reasonable improvement in the error reporting for an internal failure.
=> feat: improve reporting for internal failures

pkg/cmd/check.go, pkg/schema/constraint/lookup.go, pkg/schema/constraint/range.go
This improves the quality of error reporting for these constraints types.
=> feat: improved error reporting for range and lookups

pkg/mir/lower.go, pkg/schema/constraint/range.go
This was incorrectly being calculated in some cases.
=> fix: bitwidth calculation for range constraints

pkg/trace/printer.go
There was a very simple logical error in the trace reporting mechanism.
=> fix: trace reporting

pkg/mir/lower.go
This fixes an issue in the translation pathway which was resulting in relatively unoptimised AIR constraints.
=> fix: translation pathway

pkg/hir/lower.go, pkg/mir/constraint.go
This applies some further optimisation to eliminate empty disjuncts further up the pipeline.
=> feat: further optimise constraints

pkg/air/expr.go
This applies optimisations at the AIR level to simplify guards, thereby allowing a better comparison against the proposed v1.1
=> feat: simplify guards

pkg/hir/lower.go
This adds support for logical connectives nested within arithmetic expressions, rather than just within constraints.
=> fix: support nested logical connectives

pkg/hir/lower.go, pkg/mir/constraint.go
This puts through a relatively straightforward fix for nested inequalities which allows them to be translated when they are known constants.
=> fix: simplifying nested inequalities

pkg/asm/asm_test.go, pkg/asm/assembler.go, pkg/asm/compiler.go, pkg/asm/instruction.go, pkg/asm/instruction/add.go, pkg/asm/instruction/jmp.go, pkg/asm/instruction/jznz.go, pkg/asm/instruction/mul.go, pkg/asm/instruction/ret.go, pkg/asm/instruction/sub.go, pkg/asm/instruction/util.go, pkg/asm/parser.go, pkg/cmd/check.go, pkg/util/collection/bit/bit_set.go, testdata/asm/pow.zkasm, testdata/asm/wcp.zkasm
This adds a variety of checks to ensure that instructions are well-formed.
=> feat: check instructions well-formed

pkg/cmd/generate.go
This puts in place a simple fix for generated `Trace.java` files with respect to optional modules.
=> fix: trace generation with optional modules

pkg/cmd/generate.go, pkg/cmd/generate/class.go, pkg/cmd/generate/interface.go
This puts in place a simple modification to enable inheritance of interfaces.
=> feat: support interface inheritance

pkg/cmd/generate.go, pkg/cmd/generate/interface.go, pkg/cmd/generate/union.go, pkg/cmd/generate/util.go
This puts in place an initial (draft) implementation for the "union of all traces" approach to trace generation.  This needs real testing now.
=> feat: draft implementation of trace union

pkg/binfile/binfile.go
Since so much has change since the recent refactoring, this must be updated.
=> feat: update binary file format version

pkg/util/poly/array_poly.go, pkg/util/poly/monomial.go, pkg/util/poly/parser.go, pkg/util/poly/poly.go, pkg/util/poly/poly_test.go, pkg/util/poly/term.go, pkg/util/source/source_map.go
This puts in place a fairly minimal polynomial implementation.  All tests are passing, but there is likely to be a fair bit still to do in terms of getting in fully operational.
=> feat: minimal polynomial implementation

pkg/cmd/debug/stats.go, pkg/ir/mir/constraint.go
This improves the debug information reported at the MIR level to correctly include the various constraint forms.
=> fix: update debug information for MIR

pkg/air/schema.go, pkg/binfile/legacy/constraint.go, pkg/cmd/check.go, pkg/cmd/debug.go, pkg/cmd/root.go, pkg/cmd/trace.go, pkg/corset/ast/declaration.go, pkg/corset/compiler/parser.go, pkg/corset/compiler/preprocessor.go, pkg/corset/compiler/resolver.go, pkg/corset/compiler/translator.go, pkg/corset/compiler/typing.go, pkg/hir/lower.go, pkg/hir/schema.go, pkg/hir/substitute.go, pkg/mir/lower.go, pkg/mir/optimiser.go, pkg/mir/schema.go, pkg/schema/constraint/lookup.go, pkg/test/valid_corset_test.go
The goal here is to retrofit full support for conditional lookups on top of version `v1.0.9`.
=> feat: backport conditional lookups fully

pkg/corset/stdlib.lisp
=> Make plateau constraint consistent with spec in stdlib
