Consensys/go-corset

pkg/air/eval.go, pkg/cmd/check.go, pkg/cmd/util.go, pkg/schema/schemas.go, pkg/test/ir_test.go, pkg/util/perfstats.go
This enables support for constraint checking in batches.  The benefit of using batches is that it can help throttle the number of go-routines being generated and, hence, reduce the overall memory pressure.
=> Support constraint checking in batches

pkg/air/eval.go
This reduces memory pressure during evaluation by allocating onto the heap lazily.  Specifically, only when an operation is actually being performed.  This appears to make a fairly reasonable improvement.
=> Reduce Memory Pressure

pkg/schema/constraint/permutation.go, pkg/schema/constraint/range.go, pkg/schema/schema.go, pkg/trace/array_trace.go, pkg/trace/trace.go
This PR takes part in the prover-corset integration and exposes fields from corset to the prover that are necessary to scan a air.Schema and a trace.Trace from an external package.
=> Integration: exports the fields needed by the prover for integration

pkg/cmd/check.go, pkg/schema/schemas.go, pkg/trace/lt/reader.go
This puts through some minor tweaks to channel buffer sizes.
=> Tweak channel buffers sizes

pkg/air/schema.go, pkg/schema/constraint/permutation.go
The goal of this is purely to make a clean separation from the generic `constraint.PermutationConstraint` and the specific `air.PermutationConstraint`.
=> Declare `air.PermutationConstraint`

pkg/cmd/debug.go, pkg/cmd/trace.go, pkg/test/ir_test.go, pkg/trace/array_trace.go, pkg/trace/json/writer.go, pkg/trace/printer.go
This updates the trace --filter option to be a regex, rather than simply a prefix.
=> Enable filter using regex

pkg/cmd/trace.go
The essential problem here, however, is that this doesn't manage memory very well.  It first loads all columns into memory and then does the summaries.
=> Parallelise summarisers

pkg/cmd/check.go, pkg/schema/builder.go
This puts in place a relatively simple approach to batching for trace expansion which reuses the existing batchsize parameter intended for constraint checking.  However, this does provide an effect means to throttle memory usage on larger machines.
=> Support batching for trace expansion

pkg/air/gadgets/expand.go, pkg/air/gadgets/normalisation.go
There were two issues related to the creation of computed columns, whereby duplicate constraints could be introduced.  The issue was that, whilst duplicate columns were detected, duplicate constraints were still being added regardless.
=> fix: issues around duplicate constraints #318

pkg/cmd/trace.go, pkg/cmd/util.go
This adds support for showing the "entropy" of a column.  That is a count of how much the column changes between each line.  High entropy signals few changes between lines (e.g. all 1s as 100% entropy).
This also refactors the column summariser process to allow selection of which summaries to show.
=> Support `entropy` column summariser

pkg/hir/parser.go, pkg/schema/constraint/lookup.go, testdata/bin-dynamic.lisp, testdata/bin-static.lisp, testdata/interleave_04.lisp, testdata/lookup_01.lisp, testdata/lookup_02.lisp, testdata/lookup_03.lisp, testdata/lookup_04.lisp, testdata/lookup_05.lisp, testdata/lookup_06.lisp, testdata/lookup_07.lisp, testdata/lookup_08.lisp
This brings the syntax closer to that of the original Corset language.
=> feat: change `lookup` to `deflookup`

pkg/hir/lower.go, pkg/hir/parser.go, pkg/schema/assignment/sorted_permutation.go, pkg/schema/constraint/permutation.go, testdata/memory.lisp, testdata/module_06.lisp, testdata/module_07.lisp, testdata/mxp.lisp, testdata/permute_01.lisp, testdata/permute_02.lisp, testdata/permute_03.lisp, testdata/permute_04.lisp, testdata/permute_05.lisp, testdata/permute_06.lisp, testdata/permute_07.lisp, testdata/permute_08.lisp, testdata/permute_09.lisp
This brings the accepted source syntax closer to that of the original corset tool.  However, there is still work to do in properly separating the HIR level from the MIR / AIR levels.
=> feat: update syntax for `permutation` to `defpermutation`

pkg/schema/assignment/data_column.go, pkg/schema/assignment/sorted_permutation.go, pkg/schema/constraint/lookup.go, pkg/schema/constraint/permutation.go, pkg/schema/constraint/vanishing.go
This resets some of the naming used for the internal primitives.  This is to make a clear separation from the original corset syntax.
=> Reset internal primitive naming

pkg/binfile/constraint_set.go, pkg/hir/parser.go, pkg/schema/type.go, pkg/util/arrays.go
This is an extremely minor optimisation which attempts to reduce pressure on the heap.
=> feat: remove some occurrences of *fr.Element

pkg/binfile/constraint_set.go, pkg/schema/builder.go, pkg/trace/array_trace.go, pkg/trace/context.go
This adds support for user-defined length multipliers.  An example would be:
```
(defcolumns X Y (A :length 2))
```
=> feat: support user-defined length multipliers

pkg/binfile/constraint.go, pkg/hir/expr.go
This adds partial support for constraints with `void` context. Specifically, this is only support for constraints being read out of a binfile, and also the constant evaluation is fairly limited.  If necessary, it could be improved further down the track.
=> feat: support constraints with `void` context

pkg/cmd/util.go
The problem was that the extension was not being correctly matched for `bin` files, leading the tool to try and parse them as lisp files.
=> Fix for reading `bin` files

pkg/corset/parser.go, testdata/counter.lisp
This updates the syntax for the counter example to reflect how it originally was written in Corset.  Thus, it is now demonstrating some of the new features supported in `go-corset`.
=> Update Syntax for Counter Example

pkg/corset/ast.go, pkg/corset/binding.go, pkg/corset/parser.go, pkg/corset/resolver.go, pkg/corset/scope.go, pkg/test/invalid_corset_test.go, testdata/constant_invalid_15.lisp, testdata/constant_invalid_16.lisp, testdata/constant_invalid_17.lisp, testdata/purefun_invalid_07.lisp
This puts in place purity checking which is used in a few different contexts.  For example, in checking the body of a defpurefun definition. Likewise, constants cannot refer to defun declarations, etc.
=> Enable Purity Checking

pkg/cmd/check.go
This adds a CLI option for configuring the maximum cell width to use when generating a report.  Specifically, it means you can override the default when you want to see more / less.
=> feat: CLI option for setting report cell width

pkg/test/valid_corset_test.go, testdata/fields_01.lisp
Assertions (a.k.a properties) are now being checked propertly during testing.
=> fix: check properties during testing

pkg/corset/binding.go, pkg/corset/compiler.go, pkg/corset/expression.go, pkg/corset/preprocessor.go, pkg/corset/resolver.go, pkg/corset/translator.go, pkg/sexp/source_map.go, pkg/test/valid_corset_test.go
This puts through a reasonable change to the compiler pipeline by introducing a preprocessing stage.  This occurrs are resolution, but before translation.  The main purpose is to expand invocations, reductions and for loops.  This greatly simplies their subsequent translation.
=> feat: enable preprocessing of expressions

testdata/bin-dynamic.lisp
This updates so that the example exactly matches its original formulation.
=> feat: update `bin-dynamic` example

testdata/mxp.lisp
This updates the mxp example so that it exactly reflects its original formulation.
=> feat: update MXP example

pkg/corset/parser.go, testdata/purefun_06.lisp
This symbol is supported by the existing corset tool.  Therefore, to maintain backwards compatibility ... it must also be supported.
=> feat: support identifiers involving @

pkg/test/valid_corset_test.go, testdata/shf.lisp
This updates the shf test itself, rather than changing the go-corset implementation.  This is because, at this time, it seems like the more sensible option.  However, we may need to revisit this in the future if it ends up forcing lots of changes in the full constraint set.
=> feat: update shf test

pkg/corset/declaration.go, pkg/corset/parser.go, pkg/corset/resolver.go, pkg/corset/symbol.go, testdata/purefun_invalid_10.lisp, testdata/purefun_invalid_11.lisp, testdata/purefun_invalid_12.lisp
This improves the error reporting around functions, such as arising from defun and defpurefun.  Specifically, it highlights only the function name when there is a general error related to the function (e.g. its redeclared, etc).
=> feat: improve error reporting around functions

pkg/corset/expression.go, pkg/sexp/translator.go, pkg/test/invalid_corset_test.go, testdata/array_invalid_06.lisp
This improves the error reporting for substituted index variables. For example, when the index variable is actually out-of-range then its nice to report a sensible error about this.
=> fix: improve errors for substituted for variables

pkg/cmd/compile.go, pkg/cmd/util.go
When a directory is specified as part of a list of source files, this is now recursively searched for any lisp files contained.  Those files included are also written to log.Info.
=> feat: traverse directories for source files

pkg/sexp/parser.go
There was a minor issue relating to scaning symbols which could overrun certain symbols unexpectedly.
=> fix: for s-expression parser

pkg/corset/type.go, pkg/corset/typing.go, testdata/basic_invalid_07.lisp, testdata/fun_invalid_01.lisp, testdata/fun_invalid_02.lisp, testdata/purefun_invalid_02.lisp, testdata/purefun_invalid_03.lisp, testdata/purefun_invalid_13.lisp
This makes the type checker slightly more resiliant in the presence of type errors.
=> fix: harden type checking of invocations

pkg/corset/resolver.go
This increases the limit from 4 to 32.  Its not clear what the right limit is, but if the limit is too high then that could cause a long delay in certain situations.
=> feat: increase resolution cycle limit

pkg/cmd/compile.go, pkg/cmd/util.go
This puts in place a more robust binary file format.  Specifically, it uses an identifier and versioning to enable safe upgrades in the future. This also supports metadata in the form of an arbitrary byte sequence.
=> feat: support extended binary format

pkg/cmd/util.go
The tool now defaults to the legacy zkevm.bin when it is provided a bin file that it does not recognise.
=> feat: default to legacy zkevm.bin

pkg/cmd/util.go
This adds a simple warning which comes out when directories are being scanned for source (i.e. lisp) files.
=> feat: add warning for lispX files

pkg/binfile/constraint.go, pkg/binfile/handle.go
This tweaks the way that legacy binfiles are parsed, providing better normalisation around handles and qualified column names.
=> fix: legacy binfile names

pkg/corset/compiler/translator.go
These were previously being translated using multiplication, when in fact an `ifnot` is more appropriate.
=> fix: guard and perspective selector translation

pkg/corset/stdlib.lisp
Since these are never used, they are now dropped.
=> feat: drop specialisations for `eq` and `eq!`

pkg/corset/compiler/translator.go
Perspective selectors are reverted to being translated using multiplication, rather than a logical condition.
=> fix: translation of perspective selectors

pkg/util/field/field_index_array.go
This had mistakenly not been implemented. Fixed now.
=> fix: `FrIndexArray.Slice()`

pkg/cmd/check.go, pkg/cmd/trace.go, pkg/schema/assertion.go, pkg/schema/assignment/byte_decomposition.go, pkg/schema/assignment/computation.go, pkg/schema/assignment/computed_column.go, pkg/schema/assignment/interleave.go, pkg/schema/assignment/lexicographic_sort.go, pkg/schema/assignment/sorted_permutation.go, pkg/schema/builder.go, pkg/schema/constraint/lookup.go, pkg/schema/constraint/permutation.go, pkg/schema/constraint/range.go, pkg/schema/constraint/vanishing.go, pkg/schema/schema.go, pkg/schema/schemas.go, pkg/trace/array_trace.go, pkg/util/arrays.go, pkg/util/field/field_array.go, pkg/util/field/field_index_array.go, pkg/util/field/field_pool_array.go, testdata/basic_09.lisp
This adds support for defensive padding, and enables it by default. Defensive padding is the conversative prepending of padding rows to ensure that constraints in the active region are not clipped.  This reflects the fact that such constraints may be subject to padding by the prover anyway and, hence, we simply get ahead of the curve by doing adding it automatically.
This also adds support to the trace command to expand the trace prior to filtering, etc and also to allow defensive padding and/or spillage to be applied.
=> feat: support defensive padding

pkg/binfile/binfile.go, pkg/binfile/legacy/constraint_set.go, pkg/binfile/legacy/expr.go, pkg/corset/compiler.go, pkg/corset/compiler/translator.go, pkg/hir/context.go, pkg/hir/eval.go, pkg/hir/expr.go, pkg/hir/lisp.go, pkg/hir/lower.go, pkg/hir/term.go, pkg/hir/util.go, pkg/mir/const.go, pkg/mir/context.go, pkg/mir/eval.go, pkg/mir/expr.go, pkg/mir/lisp.go, pkg/mir/lower.go, pkg/mir/range.go, pkg/mir/term.go
This puts through a fairly major refactoring of HIR which brings it inline with the other intermediate representations.  Its not clear to me whether this is actually beneficial at this point, since it seems quite difficult to later coverage on top of this.
=> feat: refactor HIR

pkg/cmd/check.go, pkg/cmd/util.go, pkg/schema/coverage.go, pkg/util/collection/bit/bit_set.go, pkg/util/collection/bit/bit_test.go, pkg/util/collection/iter/append.go, pkg/util/collection/iter/array.go, pkg/util/collection/iter/flatten.go, pkg/util/collection/iter/iterator.go
The coverage cli command now accepts a filename which identifies where coverage data is going to be written.  The intention is that an additional command will be added ("coverage") which can be used to query coverage data, or to aggregate it, etc.
=> feat: support writing coverage data

pkg/corset/ast/binding.go, pkg/corset/compiler/intrinsics.go, pkg/corset/compiler/natives.go, pkg/corset/compiler/typing.go, testdata/purefun_07.lisp, testdata/purefun_08.lisp, testdata/purefun_invalid_13.lisp
This now prohibits overriding of functions.
=> feat: simplify notion of overriding

pkg/cmd/check.go, pkg/cmd/coverage.go, pkg/cmd/debug.go, pkg/cmd/root.go, pkg/cmd/test.go, pkg/cmd/trace.go, pkg/cmd/util.go, pkg/mir/lower.go, pkg/test/valid_corset_test.go
This puts in place some relatively simplistic optimisation levels which can, in principle, be used for investigating the cost of different optimisations.
=> feat: enable MIR optimisation levels

.gitignore, pkg/cmd/coverage/calcs.go, pkg/corset/ast/expression.go, pkg/corset/compiler/typing.go, testdata/fun_invalid_05.lisp
This fixes a situation where an invalid array access resulted in a panic.
=> fix: panic on invalid array access

pkg/binfile/binfile.go, pkg/cmd/check.go, pkg/cmd/debug.go, pkg/cmd/generate.go, pkg/cmd/inspect.go, pkg/cmd/trace.go, pkg/cmd/tracediff.go, pkg/cmd/util.go, pkg/trace/lt/header.go, pkg/trace/lt/legacy_reader.go, pkg/trace/lt/legacy_writer.go, pkg/trace/lt/trace_file.go
This adds support for a versioned `lt` file format which can include arbitrary embedded metadata.
=> feat: support versioned lt file format

pkg/cmd/coverage.go, pkg/util/table.go
This puts in place a "diff" mode which aims to faciliate comparing different coverage reports more easily.  Specifically, it highlights those which have changed.
=> feat: enable diff mode for coverage command

pkg/cmd/compile.go, pkg/cmd/util.go, pkg/corset/source_map.go
This adds support for substituting constants as part of the compile command.  This means we can substitute them when compiling from sources, and also for existing bin files.
=> feat: support constant substitution in compile

pkg/corset/stdlib.lisp
this puts in place support for a stronger variant of `if-not-zero`
=> feat: support `if-not`

pkg/corset/stdlib.lisp, testdata/mxp.lisp
This removes two functions from the standard library, namely `is-zero` and `is-not-zero`.  These were the only remaining functions which use the boolean interpretation (which no longer exists).  A key challenge here was to the update the MXP module with alternative translations which did not use these methods.
=> feat: remove deprecated stdlib functions

pkg/corset/compiler.go
The issue was around constants which have no explicit datatype given. They end up with a nil type in the compiled binary constraints file and, in such case, the constant value is used to determine the bitwidth.
=> fix: constant datatypes in trace generation

pkg/hir/substitute.go
Perhaps predictibly, the missing case was for Equation.
=> fix: missing case in hir.substituteTerm

pkg/corset/compiler/preprocessor.go, pkg/mir/lower.go
There was a problem whereby the notion of an unsafe cast was being lost during preprocessing.  This meant the benefit of such a cast was also lost.
=> fix: for unsafe casts

pkg/corset/compiler/translator.go, pkg/hir/schema.go, pkg/mir/schema.go, pkg/schema/constraint/vanishing.go
This improves the support for constraints which evaluate to known constants.  This can happen in various situations, such as when a guard exists to only enable a constraint for specific builds.
=> fix: support for constant constraints

pkg/cmd/tracediff.go, pkg/util/collection/set/sorted_set.go
This enables the "trace diff" command to work even when the columns differ between two traces.  In such, case the columns different to each trace are reported, and the diff proceeds on the set of common columns.
=> feat: support trace diff with differing columns

pkg/cmd/generate/interface.go, pkg/cmd/generate/snippets.go
This adds signatures for addMetadata() and open() to the trace interface.
=> feat: add missing signatures to trace interface

pkg/cmd/generate/union.go
This puts in place a very simple fix for unioning traces which resulted in some modules being left out by mistake.
=> feat: fix for union of all traces

pkg/cmd/root.go, pkg/corset/compiler/parser.go, pkg/ir/assignment/lexicographic_sort.go, testdata/basic/lookup_23.lisp
This relaxes the syntax to choose source selector when only 5 arguments are given.  Therefore, its not possible to specify a target selector on its own.
=> feat: relax syntax for defclookup

pkg/util/collection/array/util.go
Remove unnecessary debug print statement from CountUnique function in array/util.go that was accidentally left in production code
=> fix: remove debug print statement from CountUnique function

pkg/corset/compiler/translator.go, pkg/test/invalid_corset_test.go, testdata/invalid/lookup_invalid_11.lisp, testdata/invalid/lookup_invalid_12.lisp, testdata/invalid/lookup_invalid_13.lisp, testdata/invalid/lookup_invalid_14.lisp
This puts in place some sanity checks for lookup vectors, such as looking for potentially negative coordinates.
=> feat: sanity checks for lookup vectors

pkg/corset/compiler/preprocessor.go
This simply updates them to be properly preprocessed.
=> fix: for preprocessing concat expressions

pkg/asm/compiler/builder.go, pkg/asm/compiler/mir.go, pkg/asm/io/assignment.go, pkg/asm/io/function.go, pkg/cmd/debug/stats.go, pkg/corset/compiler/translator.go, pkg/ir/air/gadgets/lexicographic_sort.go, pkg/ir/assignment/computation.go, pkg/ir/assignment/computed_register.go, pkg/ir/assignment/lexicographic_sort.go, pkg/ir/assignment/sorted_permutation.go, pkg/ir/assignment/util.go, pkg/ir/builder/expander.go, pkg/ir/builder/expansion.go, pkg/ir/builder/splitting.go, pkg/ir/schema_builder.go, pkg/schema/assignment.go, pkg/schema/mixed_schema.go, pkg/schema/module.go, pkg/schema/schema.go, pkg/schema/uniform_schema.go
This makes the Assignment interface generic, as well as all the non-assembly assignment implementations.  In most cases, this was very straightforward as most of the plumbing had already been done.
=> feat: make assignments generic

pkg/ir/air/constraint.go
This is to enable access to the underlying constraints.
=> feat: update air.Constraint API

.github/workflows/lint.yml, .github/workflows/test.yml, .pre-commit-config.yaml, Makefile, go.mod
This updates the required version of Go to 1.24.6, and also updates the version used for golangci-lint
=> chore: update go version to 1.24.6

pkg/cmd/debug/schema.go
This ensures that column names in the generated lisp are quoted only when they contain certain characters, such as spaces, etc.  This means names for inverses will be quoted, whilst those for user-defined columns will not.
=> fix: quote column names in lisp output as needed

pkg/ir/sub.go
This puts through a fairly minor optimisation for subtractions of zero, which can be dropped.
=> feat: optimise subtractions such as X - 0 => X

pkg/cmd/inspector/inspect.go, pkg/cmd/inspector/module_state.go, pkg/cmd/inspector/nav_mode.go, pkg/cmd/inspector/query.go, pkg/util/source/bexp/parser.go
This puts through some useful upgrades to the inspector "scan" commands, including: allowing the current row to be used in a query (e.g. `$ > 100 && $ < 1000`); starting a scan from the current row; support next and previous matches to cycle through.
=> feat: upgrade inspector scan facility

pkg/asm/program/assignment.go, pkg/asm/program/module.go, pkg/ir/air/gadgets/bitwidth.go, pkg/ir/assignment/computation.go, pkg/ir/assignment/computed_register.go, pkg/ir/assignment/lexicographic_sort.go, pkg/ir/assignment/sorted_permutation.go, pkg/ir/mir/schema.go, pkg/ir/schema_builder.go, pkg/schema/assignment.go, pkg/schema/module.go
This changes the responsibility for constant substitution from being solely at the constraint level to now being at the module level.  This subsequently allows us to resolve the issue with assembly functions and substituteion (i.e. which arises because assembly functions currently have no notion of constants).
=> fix: make constant substitution a module-level concern
